openapi: 3.0.0
x-stoplight:
  id: wxajqdjnyxgi0
info:
  title: Starwipe Photo API
  version: 1.0.0
  description: The Starwipe API is a RESTful API that uses HTTP request methods and JSON-encoded responses. Our API uses resource-oriented endpoints and standard HTTP response codes.
  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.txt'
  contact:
    name: API Support
    email: apisupport@starwipe.com
    url: 'https://support.starwipe.com'
  termsOfService: 'https://starwipe.com/terms'
paths:
  /users:
    post:
      summary: Create User
      operationId: createUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserCreate'
        description: Request body description
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: 'Bad Request, likely due to missing or invalid `username` or `email`'
      x-stoplight:
        id: g4xtxpsikzqzm
      description: Create a new user
      tags:
        - Users
      parameters: []
  '/users/{user_id}':
    parameters:
      - schema:
          type: string
        name: user_id
        in: path
        required: true
    put:
      summary: Modify User
      operationId: editUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserEdit'
      responses:
        '200':
          description: User edited successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
      x-stoplight:
        id: yxk6iq23y08xx
      tags:
        - Users
    delete:
      summary: Delete User
      operationId: deleteUser
      responses:
        '204':
          description: User deleted successfully
      x-stoplight:
        id: jhiywkxbew2jj
      tags:
        - Users
  '/users/{user_id}/invite':
    parameters:
      - schema:
          type: string
        name: user_id
        in: path
        required: true
  /galleries:
    post:
      summary: Create Gallery
      operationId: createGallery
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GalleryCreate'
      responses:
        '201':
          description: Album created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Gallery'
          headers:
            location:
              schema:
                type: string
              description: 'https://api.starwipe.com/v1/albums/{albumId}'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      x-stoplight:
        id: uywncs1zrkjqe
      description: Create a new album. Title is required. Description and category are optional.
      parameters:
        - schema:
            type: string
            maxLength: 60
            example: Costa Rica
          in: query
          name: title
          description: Give your album a title
          required: true
        - schema:
            type: string
            maxLength: 250
            example: family trip to Costa Rica Feb 2023
          in: query
          name: desc
          description: Brief text description of the album
        - schema:
            type: string
          in: query
          name: category
          description: Album category
        - schema:
            type: string
          in: query
        - schema:
            type: string
          in: query
      tags:
        - Galleries
    parameters: []
  '/galleries/{gallery_id}':
    parameters:
      - schema:
          type: string
        name: gallery_id
        in: path
        required: true
    put:
      summary: Modify Gallery
      operationId: editGallery
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GalleryEdit'
      responses:
        '200':
          description: Gallery edited successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Gallery'
      x-stoplight:
        id: ixpa8c8pywgo4
      tags:
        - Galleries
    get:
      summary: Get Gallery
      operationId: downloadGallery
      responses:
        '200':
          description: Gallery downloaded successfully
          content:
            application/zip:
              schema:
                type: string
                format: binary
      x-stoplight:
        id: ssvsya3qgbohq
      tags:
        - Galleries
components:
  schemas:
    UserCreate:
      type: object
      x-examples:
        Example 1:
          username: maxpower55
          email: max.power@yahoo.com
      properties:
        username:
          type: string
          x-stoplight:
            id: 9j1k0psu19yal
        email:
          type: string
          x-stoplight:
            id: 79bin2399uj7h
      required:
        - username
        - email
    UserEdit:
      type: object
      properties:
        username:
          type: string
      x-stoplight:
        id: aw378mlkmycvz
    User:
      type: object
      x-examples:
        Example 1:
          user_id: '1000567345'
          username: maxpower55
          email: max.power@yahoo.com
          date_created: '2023-10-25T01:09:41.892Z'
          first_name: Max
          last_name: Power
          gallery_count: 0
          image_count: 0
          privacy_enabled: true
          subscription: basic
          object: user
      title: User Object
      properties:
        user_id:
          type: string
          description: Unique ID of the user
          example: '1000567345'
        username:
          type: string
          description: User-created unique identifier
          example: maxpower55
        email:
          type: string
          description: Email address of the user
          format: email
          example: max.power@yahoo.com
        date_created:
          type: string
          description: Date the user account was created in ISO 8601 format
          format: date-time
        first_name:
          description: First name of user
          type: string
        last_name:
          description: Last name of user
          type: string
        gallery_count:
          type: integer
          description: Number of galleries the user has created
        image_count:
          type: integer
          description: Number of photos the user has uploaded
        privacy_enabled:
          type: boolean
          description: 'If `true`, the user''s profile is not searchable by other users'
          default: true
        subscription:
          type: string
          description: 'Can be `basic`, `starter`, or `premium`'
        object:
          type: string
          description: Type of the resource
      description: ''
    Invitation:
      type: object
      properties:
        invitedUserId:
          type: string
          format: uuid
      x-stoplight:
        id: e7fn2nzpfdukf
    GalleryCreate:
      type: object
      properties:
        name:
          type: string
      x-stoplight:
        id: 0n94pxwq3kiz2
    GalleryEdit:
      type: object
      properties:
        name:
          type: string
      x-stoplight:
        id: 2ip5hiajcwndr
    GalleryArchive:
      type: object
      properties:
        name:
          type: string
      x-stoplight:
        id: 68pz5a5s4t7u1
    Gallery:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
      x-stoplight:
        id: nom0hm1j15rvw
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-KEY
  responses: {}
  requestBodies:
    UserCreate:
      content:
        application/json:
          schema:
            type: object
            properties:
              username:
                type: string
                x-stoplight:
                  id: xfgtmyh7hxwm8
              email:
                type: string
                x-stoplight:
                  id: 2riu2f71tnd0b
            required:
              - username
              - email
servers:
  - url: 'https://api.starwipe.com/v1'
x-internal: false
tags:
  - name: Galleries
  - name: Images
  - name: Users
