openapi: 3.0.0
info:
  title: Photo Hosting App API
  version: 1.0.0
  description: An API for managing users and galleries in a photo hosting app.

paths:
  /users:
    post:
      summary: Create a user
      operationId: createUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserCreate'
      responses:
        201:
          description: User created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

  /users/{userId}:
    parameters:
      - name: userId
        in: path
        required: true
        description: ID of the user to edit or delete
        schema:
          type: string
          format: uuid

    put:
      summary: Edit a user by ID
      operationId: editUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserEdit'
      responses:
        200:
          description: User edited successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

    delete:
      summary: Delete a user by ID
      operationId: deleteUser
      responses:
        204:
          description: User deleted successfully

  /users/{userId}/invite:
    post:
      summary: Invite a user to collaborate
      operationId: inviteUser
      parameters:
        - name: userId
          in: path
          required: true
          description: ID of the user to invite
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Invitation'
      responses:
        201:
          description: User invited successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Invitation'

  /galleries:
    post:
      summary: Create a gallery
      operationId: createGallery
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GalleryCreate'
      responses:
        201:
          description: Gallery created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Gallery'

  /galleries/{galleryId}:
    parameters:
      - name: galleryId
        in: path
        required: true
        description: ID of the gallery to edit, archive, or download
        schema:
          type: string
          format: uuid

    put:
      summary: Edit a gallery by ID
      operationId: editGallery
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GalleryEdit'
      responses:
        200:
          description: Gallery edited successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Gallery'

    #put:
    #  summary: Archive a gallery by ID
    #  operationId: archiveGallery
    #  requestBody:
    #    required: true
    #    content:
    #      application/json:
    #        schema:
    #          $ref: '#/components/schemas/GalleryArchive'
    #  responses:
    #    200:
    #      description: Gallery archived successfully
    #      content:
    #        application/json:
    #          schema:
    #            $ref: '#/components/schemas/Gallery'

    get:
      summary: Download a gallery by ID
      operationId: downloadGallery
      responses:
        200:
          description: Gallery downloaded successfully
          content:
            application/zip:
              schema:
                type: string
                format: binary

components:
  schemas:
    UserCreate:
      type: object
      properties:
        username:
          type: string

    UserEdit:
      type: object
      properties:
        username:
          type: string

    User:
      type: object
      properties:
        id:
          type: string
          format: uuid
        username:
          type: string

    Invitation:
      type: object
      properties:
        invitedUserId:
          type: string
          format: uuid

    GalleryCreate:
      type: object
      properties:
        name:
          type: string

    GalleryEdit:
      type: object
      properties:
        name:
          type: string

    GalleryArchive:
      type: object
      properties:
        name:
          type: string

    Gallery:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string

  #errors:
  #  BadRequest:
  #    description: Bad request. Please check your request parameters.
  #  NotFound:
  #    description: The requested resource was not found.
  #  InternalServerError:
  #    description: An internal server error occurred. Please try again later.
